<?xml version="1.0"?>
<package format="3">
  <name>obstacle_detector_ros</name>
  <version>5.1.0</version>
  <description>LiDAR loading and railway obstacle detection for ROS 2 Humble.</description>
  <maintainer email="tactical-inventor@users.noreply.github.com">NIIstovye</maintainer>
  <license>Proprietary</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>rcl_interfaces</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-scipy</exec_depend>
  <exec_depend>python3-numba</exec_depend>
  <test_depend>python3-pytest</test_depend>
  <export><build_type>ament_python</build_type></export>
</package>
